import numpy as np
import tensorflow as tf
from tf_agents.typing import types
from tf_agents.specs import array_spec, tensor_spec

numeric_feature_names = [
    'char_defence_defence_black',
    'char_defence_defence_blue',
    'char_defence_defence_brown',
    'char_defence_defence_cyan',
    'char_defence_defence_gray',
    'char_defence_defence_green',
    'char_defence_defence_orange',
    'char_defence_defence_pink',
    'char_defence_defence_red',
    'char_defence_defence_violet',
    'char_defence_defence_white',
    'char_defence_defence_yellow',
    'char_effect_euphoria_euphoricsource_amount',
    'char_effect_euphoria_ultimateearly_amount',
    'char_effect_milana_mintmist_turnsleft',
    'char_effect_milana_stolenhp_amount',
    'char_effect_ruby_cannotheal_turnsleft',
    'char_effect_ruby_doubledamage_turnsleft',
    'char_effect_speed_blacktokens_number',
    'char_effect_speed_greentokens_number',
    'char_effect_structure_iboost_amount',
    'char_effect_structure_slayers_threshold',
    'char_effect_z89_ultimateslow_amount',
    'char_hp',
    'char_maxhp',
    'char_skill0_cooldown',
    'char_skill0_unlock_turn',
    'char_skill1_cooldown',
    'char_skill1_unlock_turn',
    'char_skill2_cooldown',
    'char_skill2_unlock_turn',
    'char_skill3_cooldown',
    'char_skill3_unlock_turn',
    'opp_defence_defence_black',
    'opp_defence_defence_blue',
    'opp_defence_defence_brown',
    'opp_defence_defence_cyan',
    'opp_defence_defence_gray',
    'opp_defence_defence_green',
    'opp_defence_defence_orange',
    'opp_defence_defence_pink',
    'opp_defence_defence_red',
    'opp_defence_defence_violet',
    'opp_defence_defence_white',
    'opp_defence_defence_yellow',
    'opp_effect_euphoria_euphoricsource_amount',
    'opp_effect_euphoria_ultimateearly_amount',
    'opp_effect_milana_mintmist_turnsleft',
    'opp_effect_milana_stolenhp_amount',
    'opp_effect_ruby_cannotheal_turnsleft',
    'opp_effect_ruby_doubledamage_turnsleft',
    'opp_effect_speed_blacktokens_number',
    'opp_effect_speed_greentokens_number',
    'opp_effect_structure_iboost_amount',
    'opp_effect_structure_slayers_threshold',
    'opp_effect_z89_ultimateslow_amount',
    'opp_hp',
    'opp_maxhp',
    'opp_skill0_cooldown',
    'opp_skill0_unlock_turn',
    'opp_skill1_cooldown',
    'opp_skill1_unlock_turn',
    'opp_skill2_cooldown',
    'opp_skill2_unlock_turn',
    'opp_skill3_cooldown',
    'opp_skill3_unlock_turn',
    'turnnum'
]
binary_feature_names = [
    'asopp',
    'char_effect_euphoria_euphoricheal',
    'char_effect_speed_damagereduced',
    'char_effect_speed_defencereduced',
    'char_effect_speed_spedup',
    'char_effect_storyteller_controlled',
    'char_effect_structure_lastchance',
    'char_skill0_is_available',
    'char_skill1_is_available',
    'char_skill2_is_available',
    'char_skill3_is_available',
    'goingfirst',
    'opp_effect_euphoria_euphoricheal',
    'opp_effect_speed_damagereduced',
    'opp_effect_speed_defencereduced',
    'opp_effect_speed_spedup',
    'opp_effect_storyteller_controlled',
    'opp_effect_structure_lastchance',
    'opp_skill0_is_available',
    'opp_skill1_is_available',
    'opp_skill2_is_available',
    'opp_skill3_is_available'
]
colours = [
    '',
    'black',
    'blue',
    'brown',
    'cyan',
    'gray',
    'green',
    'orange',
    'pink',
    'red',
    'violet',
    'white',
    'yellow',
]
skills = [-1, 0, 1, 2, 3]
chars = [1, 8, 9, 10, 33, 51, 119]
categorical_feature_names = {
    'char_effect_storyteller_cannotuse_colour': colours,
    'char_lastusedskill': skills,
    'char_number': chars,
    'char_skill0_colour': colours,
    'char_skill1_colour': colours,
    'char_skill2_colour': colours,
    'char_skill3_colour': colours,
    'opp_effect_storyteller_cannotuse_colour': colours,
    'opp_lastusedskill': skills,
    'opp_number': chars,
    'opp_skill0_colour': colours,
    'opp_skill1_colour': colours,
    'opp_skill2_colour': colours,
    'opp_skill3_colour': colours
}

sample = {
        "asopp": False,
        "char_defence_defence_black": -2,
        "char_defence_defence_blue": 0,
        "char_defence_defence_brown": 0,
        "char_defence_defence_cyan": 1,
        "char_defence_defence_gray": 0,
        "char_defence_defence_green": 1,
        "char_defence_defence_orange": -1,
        "char_defence_defence_pink": 0,
        "char_defence_defence_red": 0,
        "char_defence_defence_violet": -1,
        "char_defence_defence_white": 2,
        "char_defence_defence_yellow": 1,
        "char_effect_euphoria_euphoricheal": False,
        "char_effect_euphoria_euphoricsource_amount": 0,
        "char_effect_euphoria_ultimateearly_amount": 0,
        "char_effect_milana_mintmist_turnsleft": 0,
        "char_effect_milana_stolenhp_amount": 108,
        "char_effect_ruby_cannotheal_turnsleft": 0,
        "char_effect_ruby_doubledamage_turnsleft": 0,
        "char_effect_speed_blacktokens_number": 0,
        "char_effect_speed_damagereduced": False,
        "char_effect_speed_defencereduced": False,
        "char_effect_speed_greentokens_number": 0,
        "char_effect_speed_spedup": False,
        "char_effect_storyteller_cannotuse_colour": "",
        "char_effect_storyteller_controlled": False,
        "char_effect_structure_iboost_amount": 0,
        "char_effect_structure_lastchance": False,
        "char_effect_structure_slayers_threshold": 0,
        "char_effect_z89_ultimateslow_amount": 0,
        "char_hp": 114,
        "char_lastusedskill": 0,
        "char_maxhp": 114,
        "char_number": 51,
        "char_skill0_colour": "green",
        "char_skill0_cooldown": 0,
        "char_skill0_is_available": True,
        "char_skill0_unlock_turn": 0,
        "char_skill1_colour": "white",
        "char_skill1_cooldown": 0,
        "char_skill1_is_available": True,
        "char_skill1_unlock_turn": 0,
        "char_skill2_colour": "white",
        "char_skill2_cooldown": 2,
        "char_skill2_is_available": True,
        "char_skill2_unlock_turn": 0,
        "char_skill3_colour": "cyan",
        "char_skill3_cooldown": 0,
        "char_skill3_is_available": True,
        "char_skill3_unlock_turn": 8,
        "goingfirst": True,
        "opp_defence_defence_black": 0,
        "opp_defence_defence_blue": -2,
        "opp_defence_defence_brown": 1,
        "opp_defence_defence_cyan": 1,
        "opp_defence_defence_gray": 0,
        "opp_defence_defence_green": 0,
        "opp_defence_defence_orange": -1,
        "opp_defence_defence_pink": 0,
        "opp_defence_defence_red": 4,
        "opp_defence_defence_violet": 0,
        "opp_defence_defence_white": 0,
        "opp_defence_defence_yellow": 2,
        "opp_effect_euphoria_euphoricheal": False,
        "opp_effect_euphoria_euphoricsource_amount": 0,
        "opp_effect_euphoria_ultimateearly_amount": 0,
        "opp_effect_milana_mintmist_turnsleft": 0,
        "opp_effect_milana_stolenhp_amount": 0,
        "opp_effect_ruby_cannotheal_turnsleft": 0,
        "opp_effect_ruby_doubledamage_turnsleft": 2,
        "opp_effect_speed_blacktokens_number": 0,
        "opp_effect_speed_damagereduced": False,
        "opp_effect_speed_defencereduced": False,
        "opp_effect_speed_greentokens_number": 0,
        "opp_effect_speed_spedup": False,
        "opp_effect_storyteller_cannotuse_colour": "",
        "opp_effect_storyteller_controlled": False,
        "opp_effect_structure_iboost_amount": 0,
        "opp_effect_structure_lastchance": False,
        "opp_effect_structure_slayers_threshold": 0,
        "opp_effect_z89_ultimateslow_amount": 0,
        "opp_hp": 2,
        "opp_lastusedskill": 0,
        "opp_maxhp": 110,
        "opp_number": 10,
        "opp_skill0_colour": "yellow",
        "opp_skill0_cooldown": 0,
        "opp_skill0_is_available": True,
        "opp_skill0_unlock_turn": 0,
        "opp_skill1_colour": "red",
        "opp_skill1_cooldown": 0,
        "opp_skill1_is_available": True,
        "opp_skill1_unlock_turn": 0,
        "opp_skill2_colour": "cyan",
        "opp_skill2_cooldown": 1,
        "opp_skill2_is_available": True,
        "opp_skill2_unlock_turn": 0,
        "opp_skill3_colour": "red",
        "opp_skill3_cooldown": 0,
        "opp_skill3_is_available": True,
        "opp_skill3_unlock_turn": 0,
        "turnnum": 10
    }

def full_format_preprocessing():
    inputs = {}
    specs = {}
    for name, item in sample.items():
        if type(item) == str:
            dtype = tf.string
        elif name in categorical_feature_names:
            dtype = tf.int64
        elif name in binary_feature_names:
            dtype = tf.bool
        else:
            # dtype = tf.float32
            dtype = tf.int64

        inputs[name] = tf.keras.Input(shape=(1,), name=name, dtype=dtype)
        specs[name] = tensor_spec.TensorSpec(shape=(1,), dtype=dtype)
    
    preprocessed = []

    for name in binary_feature_names:
        inp = inputs[name]
        preprocessed.append(tf.cast(inp, tf.float32))

    numeric_inputs = []
    for name in numeric_feature_names:
        numeric_inputs.append(inputs[name])

    numeric_inputs = tf.keras.layers.Concatenate(axis=-1)(numeric_inputs)
    preprocessed.append(tf.cast(numeric_inputs, tf.float32))

    for name, vocab in categorical_feature_names.items():
        if len(vocab) < 2:
            continue

        if type(vocab[0]) is str:
            lookup = tf.keras.layers.StringLookup(vocabulary=vocab, output_mode='one_hot')
        else:
            lookup = tf.keras.layers.IntegerLookup(vocabulary=vocab, output_mode='one_hot')

        x = inputs[name]
        x = lookup(x)
        preprocessed.append(x)
    
    preprocessed_result = tf.keras.layers.Concatenate(axis=1)(preprocessed)
    return tf.keras.Model(inputs, preprocessed_result), specs

def full_format_spec() -> dict[str, types.NestedArraySpec]:
    bool_spec = array_spec.ArraySpec(shape=(1,), dtype=bool)
    int_spec = array_spec.ArraySpec(shape=(1,), dtype=np.int64)
    str_spec = array_spec.ArraySpec(shape=(1,), dtype=np.dtypes.StrDType)

    return {
        "asopp": bool_spec,
        "char_defence_defence_black": int_spec,
        "char_defence_defence_blue": int_spec,
        "char_defence_defence_brown": int_spec,
        "char_defence_defence_cyan": int_spec,
        "char_defence_defence_gray": int_spec,
        "char_defence_defence_green": int_spec,
        "char_defence_defence_orange": int_spec,
        "char_defence_defence_pink": int_spec,
        "char_defence_defence_red": int_spec,
        "char_defence_defence_violet": int_spec,
        "char_defence_defence_white": int_spec,
        "char_defence_defence_yellow": int_spec,
        "char_effect_euphoria_euphoricheal": bool_spec,
        "char_effect_euphoria_euphoricsource_amount": int_spec,
        "char_effect_euphoria_ultimateearly_amount": int_spec,
        "char_effect_milana_mintmist_turnsleft": int_spec,
        "char_effect_milana_stolenhp_amount": int_spec,
        "char_effect_ruby_cannotheal_turnsleft": int_spec,
        "char_effect_ruby_doubledamage_turnsleft": int_spec,
        "char_effect_speed_blacktokens_number": int_spec,
        "char_effect_speed_damagereduced": bool_spec,
        "char_effect_speed_defencereduced": bool_spec,
        "char_effect_speed_greentokens_number": int_spec,
        "char_effect_speed_spedup": bool_spec,
        "char_effect_storyteller_cannotuse_colour": str_spec,
        "char_effect_storyteller_controlled": bool_spec,
        "char_effect_structure_iboost_amount": int_spec,
        "char_effect_structure_lastchance": bool_spec,
        "char_effect_structure_slayers_threshold": int_spec,
        "char_effect_z89_ultimateslow_amount": int_spec,
        "char_hp": int_spec,
        "char_lastusedskill": int_spec,
        "char_maxhp": int_spec,
        "char_number": int_spec,
        "char_skill0_colour": str_spec,
        "char_skill0_cooldown": int_spec,
        "char_skill0_is_available": bool_spec,
        "char_skill0_unlock_turn": int_spec,
        "char_skill1_colour": str_spec,
        "char_skill1_cooldown": int_spec,
        "char_skill1_is_available": bool_spec,
        "char_skill1_unlock_turn": int_spec,
        "char_skill2_colour": str_spec,
        "char_skill2_cooldown": int_spec,
        "char_skill2_is_available": bool_spec,
        "char_skill2_unlock_turn": int_spec,
        "char_skill3_colour": str_spec,
        "char_skill3_cooldown": int_spec,
        "char_skill3_is_available": bool_spec,
        "char_skill3_unlock_turn": int_spec,
        "goingfirst": bool_spec,
        "opp_defence_defence_black": int_spec,
        "opp_defence_defence_blue": int_spec,
        "opp_defence_defence_brown": int_spec,
        "opp_defence_defence_cyan": int_spec,
        "opp_defence_defence_gray": int_spec,
        "opp_defence_defence_green": int_spec,
        "opp_defence_defence_orange": int_spec,
        "opp_defence_defence_pink": int_spec,
        "opp_defence_defence_red": int_spec,
        "opp_defence_defence_violet": int_spec,
        "opp_defence_defence_white": int_spec,
        "opp_defence_defence_yellow": int_spec,
        "opp_effect_euphoria_euphoricheal": bool_spec,
        "opp_effect_euphoria_euphoricsource_amount": int_spec,
        "opp_effect_euphoria_ultimateearly_amount": int_spec,
        "opp_effect_milana_mintmist_turnsleft": int_spec,
        "opp_effect_milana_stolenhp_amount": int_spec,
        "opp_effect_ruby_cannotheal_turnsleft": int_spec,
        "opp_effect_ruby_doubledamage_turnsleft": int_spec,
        "opp_effect_speed_blacktokens_number": int_spec,
        "opp_effect_speed_damagereduced": bool_spec,
        "opp_effect_speed_defencereduced": bool_spec,
        "opp_effect_speed_greentokens_number": int_spec,
        "opp_effect_speed_spedup": bool_spec,
        "opp_effect_storyteller_cannotuse_colour": str_spec,
        "opp_effect_storyteller_controlled": bool_spec,
        "opp_effect_structure_iboost_amount": int_spec,
        "opp_effect_structure_lastchance": bool_spec,
        "opp_effect_structure_slayers_threshold": int_spec,
        "opp_effect_z89_ultimateslow_amount": int_spec,
        "opp_hp": int_spec,
        "opp_lastusedskill": int_spec,
        "opp_maxhp": int_spec,
        "opp_number": int_spec,
        "opp_skill0_colour": str_spec,
        "opp_skill0_cooldown": int_spec,
        "opp_skill0_is_available": bool_spec,
        "opp_skill0_unlock_turn": int_spec,
        "opp_skill1_colour": str_spec,
        "opp_skill1_cooldown": int_spec,
        "opp_skill1_is_available": bool_spec,
        "opp_skill1_unlock_turn": int_spec,
        "opp_skill2_colour": str_spec,
        "opp_skill2_cooldown": int_spec,
        "opp_skill2_is_available": bool_spec,
        "opp_skill2_unlock_turn": int_spec,
        "opp_skill3_colour": str_spec,
        "opp_skill3_cooldown": int_spec,
        "opp_skill3_is_available": bool_spec,
        "opp_skill3_unlock_turn": int_spec,
        "turnnum": int_spec
    }