services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 127.0.0.1:5432:5432

  valkey:
    image: valkey/valkey:8.0.2-alpine
    ports:
      - 127.0.0.1:6379:6379