
# python wrapper for package github.com/ShmaykhelDuo/battler/internal/game/characters within overall package game
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy pkg -exclude=model,ml1,ml2,moveml ../../internal/game ../../internal/bot context encoding/json

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _game
from . import go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from game import characters
# and then refer to everything using characters. prefix
# packages imported by this package listed below:




# ---- Types ---


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---
def Hmm():
	"""
	Hmm Gets Go Variable: characters.Hmm
	
	"""
	return _game.characters_Hmm()

def Set_Hmm(value):
	"""
	Set_Hmm Sets Go Variable: characters.Hmm
	
	"""
	if isinstance(value, go.GoClass):
		_game.characters_Set_Hmm(value.handle)
	else:
		_game.characters_Set_Hmm(value)



# ---- Interfaces ---


# ---- Structs ---


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---


# ---- Functions ---


