
# python wrapper for package github.com/ShmaykhelDuo/battler/internal/bot/ml within overall package game
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy pkg -exclude=model,ml1,ml2,moveml ../../internal/game ../../internal/bot context encoding/json

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _game
from . import go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from game import ml
# and then refer to everything using ml. prefix
# packages imported by this package listed below:

from . import json
from . import minimax
from . import match



# ---- Types ---

# Python type for map map[string]any
class Map_string_any(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_game.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_game.IncRef(self.handle)
		else:
			self.handle = _game.Map_string_any_CTor()
			_game.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Mapping):
					raise TypeError('Map_string_any.__init__ takes a mapping as argument')
				for k, v in args[0].items():
					_game.Map_string_any_set(self.handle, k, v)
	def __del__(self):
		_game.DecRef(self.handle)
	def __str__(self):
		s = 'game.Map_string_any len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' {'
		if len(self) < 120:
			for k, v in self.items():
				s += str(k) + '=' + str(v) + ', '
		return s + '}'
	def __repr__(self):
		s = 'game.Map_string_any({'
		for k, v in self.items():
			s += str(k) + '=' + str(v) + ', '
		return s + '})'
	def __len__(self):
		return _game.Map_string_any_len(self.handle)
	def __getitem__(self, key):
		return any(handle=_game.Map_string_any_elem(self.handle, key))
	def __setitem__(self, key, value):
		_game.Map_string_any_set(self.handle, key, value.handle)
	def __delitem__(self, key):
		return _game.Map_string_any_delete(self.handle, key)
	def keys(self):
		return go.Slice_string(handle=_game.Map_string_any_keys(self.handle))
	def values(self):
		vls = []
		kys = self.keys()
		for k in kys:
			vls.append(self[k])
		return vls
	def items(self):
		vls = []
		kys = self.keys()
		for k in kys:
			vls.append((k, self[k]))
		return vls
	def __iter__(self):
		return iter(self.items())
	def __contains__(self, key):
		return _game.Map_string_any_contains(self.handle, key)


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---


# ---- Interfaces ---

# Python type for interface ml.Format
class Format(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_game.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_game.IncRef(self.handle)
		else:
			self.handle = 0
	def Row(self, state):
		"""Row(object state) object"""
		return Map_string_any(handle=_game.ml_Format_Row(self.handle, state.handle))


# ---- Structs ---


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---


# ---- Functions ---
def ExportDataset(out, data, format):
	"""ExportDataset(object out, []object data, object format) str"""
	return _game.ml_ExportDataset(out.handle, data.handle, format.handle)


