on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Install libtensorflow
        run: |
          FILENAME=libtensorflow-cpu-linux-x86_64-2.15.0.tar.gz
          wget -q --no-check-certificate https://storage.googleapis.com/tensorflow/libtensorflow/${FILENAME}
          sudo tar -C /usr/local -xzf ${FILENAME}
          sudo ldconfig /usr/local/lib
      - name: Download assets
        run: |
          wget -q "$IMAGES_URL" -O images.zip
          unzip images.zip -d images/
          wget -q "$MODELS_URL" -O models.zip
          unzip models.zip -d ml/
        env:
          IMAGES_URL: ${{ secrets.IMAGES_URL }}
          MODELS_URL: ${{ secrets.MODELS_URL }}
      - name: Build
        run: go build -v ./cmd/... ./internal/...
      - name: Test
        run: go build -v ./cmd/... ./internal/...
